name: hello_stranger
description: 畢業專題 App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1-alpha

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0 # 自動調整字體大小
  cloud_firestore: ^3.4.6 # Firebase Firestore Database
  cupertino_icons: ^1.0.5
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.7.0 # Firebase Authentication
  firebase_core: ^1.21.1 # Firebase
  firebase_messaging: ^13.0.0 # Firebase Cloud Messaging
  firebase_storage: ^10.3.7 # Firebase Cloud Storage
  flutter_spinkit: ^5.1.0 # 按鈕載入動畫
  flutter_reactive_ble: ^5.0.2
  fluttertoast: ^8.0.9 # toast
  image_cropper: ^3.0.0 # 照片裁剪
  image_picker: ^0.8.5+3 # 照片選擇
  package_info_plus: ^1.4.3+1 # 取得版本號
  path_provider: ^2.0.11 # 本地檔案讀寫
  pin_code_fields: ^7.4.0 # 手機認證碼區塊
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo_foreground.png
    - assets/default_account_photo.png
